//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ETek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public int DefectId { get; set; }
        public int CustomerID { get; set; }
        public int Priority { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string description { get; set; }
    }
}
